version: '3.7'

services:
  stub:
    image: node
    volumes:
      - './stub:/app'
    working_dir: '/app'
    environment:
      PORT: '3000'
    entrypoint: '/bin/bash -c'
    command:
      - |
        npm install
        npm run start:dev
    networks: [ 'my-network' ]
    ports: [ '3000:3000']

  roundup:
    image: maven:3.6-jdk-11-slim
    volumes:
      - './roundup:/app'
      - 'maven-cache:/root/.m2'
    working_dir: '/app'
    environment:
      STARLING_HOST: http://stub:3000
      ROUNDUP_ACCESS_TOKEN: ${ROUNDUP_ACCESS_TOKEN:-My-Roundup-Access-Token}
    entrypoint: '/bin/bash -c'
    networks: [ 'my-network' ]

networks:
  my-network:

volumes:
  maven-cache:
